workspace:
  base: /test
  path: oe_profile

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    environment:
     - DOCUMENT_ROOT=/test/oe_profile
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

pipeline:
  composer-install:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    volumes:
      - /cache:/cache
    commands:
      - composer update ${COMPOSER_BOUNDARY}

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./vendor/bin/behat

matrix:
  IMAGE_PHP:
    - fpfis/httpd-php-dev:5.6
    - fpfis/httpd-php-dev:7.1
  COMPOSER_BOUNDARY:
    - '--prefer-lowest'
    - ''
