workspace:
  base: /test
  path: oe_profile

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
     - DOCUMENT_ROOT=/test/oe_profile
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

matrix:
  DRUPAL_VERSION:
    - 8.6.x

pipeline:

  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer require webflo/drupal-core-require-dev:${DRUPAL_VERSION=8.6.x}

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat
