sudo: required

git:
  depth: 1

services:
  - docker
  - docker-compose

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0

before_install:
  - docker-compose build
  - docker-compose up --no-start
  - docker-compose start

install:
  - docker-compose exec -u web web composer install

script:
  - docker-compose exec -u web web ./vendor/bin/grumphp run

notifications:
  email: false

